<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(VersionNumber)' == ''">
		<VersionNumber>3.0-debug</VersionNumber>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFrameworks>net10.0;net48;netstandard2.0</TargetFrameworks>
	</PropertyGroup>
  <PropertyGroup>
    <PackageId>SanteDB.Matcher</PackageId>
    <Title>SanteDB.Matcher</Title>
    <Version>$(VersionNumber)</Version>
    <Description>SanteDB Matching Plugin. Provides deterministic and probabalistic matching algorithms for the SanteDB persistence engine.</Description>
    <Authors>SanteSuite Contributors</Authors>
    <PackageTags>SanteDB</PackageTags>
    <RepositoryUrl>https://github.com/santedb/santedb-match</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
	    <Product>SanteDB</Product>
    <Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
    <PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
    <PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
    <Company>SanteSuite Contributors</Company>
  </PropertyGroup>
    
  <ItemGroup>
    <None Remove="Docker\MatchingFeature.xml" />
    <None Remove="Resources\MatchConfiguration.xslt" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Docker\MatchingFeature.xml" />
    <EmbeddedResource Include="Resources\MatchConfiguration.xslt" />
  </ItemGroup>  
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>      
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
      <ItemGroup>
        <PackageReference Include="SanteDB.Core.Applets" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.OrmLite" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Docker.Core" Version="$(VersionNumber)" />
				<PackageReference Include="SanteDB.Rest.Common" Version="$(VersionNumber)" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
        <ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
        <ProjectReference Include="..\..\santedb-applets\SanteDB.Core.Applets\SanteDB.Core.Applets.csproj" />
        <ProjectReference Include="..\..\santedb-orm\SanteDB.OrmLite\SanteDB.OrmLite.csproj" />
        <ProjectReference Include="..\..\santedb-docker\SanteDB.Docker.Core\SanteDB.Docker.Core.csproj" />
				<ProjectReference Include="..\..\santedb-restsvc\SanteDB.Rest.Common\SanteDB.Rest.Common.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <None Include="..\SanteDB.licenseheader">
      <Link>SanteDB.licenseheader</Link>
    </None>
    <None Include="Schema\MatcherDefinition.xsd">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="[13.0.4,13.1)" />
    <PackageReference Include="Phonix" Version="1.0.2" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\MatchConfiguration.xslt" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Data\*.dataset">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>